class PhoneNumberAlreadyExistsError(Exception):
    """Исключение, выбрасываемое, когда номер телефона уже существует."""
    pass
